version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: ecom-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecom
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mysql_data:  # Named volume for data persistence